// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpvu2lcMR0XG-3Izgka-AmK9hcm4RQYZk',
    appId: '1:632357327788:web:66b12f9b0b871cc9ffa009',
    messagingSenderId: '632357327788',
    projectId: 'vetconnect-rural-2026-v1',
    authDomain: 'vetconnect-rural-2026-v1.firebaseapp.com',
    storageBucket: 'vetconnect-rural-2026-v1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYxOu0zRsfe9dQUgS-8xl9biSRe9Y20fY',
    appId: '1:632357327788:android:d19480054a098f9affa009',
    messagingSenderId: '632357327788',
    projectId: 'vetconnect-rural-2026-v1',
    storageBucket: 'vetconnect-rural-2026-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5mxBEG5knAGKkgCuZ_EDTc8a0_dyfb84',
    appId: '1:632357327788:ios:4d2ec7f2f9769b1fffa009',
    messagingSenderId: '632357327788',
    projectId: 'vetconnect-rural-2026-v1',
    storageBucket: 'vetconnect-rural-2026-v1.firebasestorage.app',
    iosClientId: '632357327788-2rgkmmqihr2bv2qo8bvotisc5msj4lh5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5mxBEG5knAGKkgCuZ_EDTc8a0_dyfb84',
    appId: '1:632357327788:ios:9d5db6c0dbbf925cffa009',
    messagingSenderId: '632357327788',
    projectId: 'vetconnect-rural-2026-v1',
    storageBucket: 'vetconnect-rural-2026-v1.firebasestorage.app',
    iosClientId: '632357327788-3un3k2ue32oh3e9tsg5n1k41v59mdj3c.apps.googleusercontent.com',
    iosBundleId: 'com.vetconnect.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpvu2lcMR0XG-3Izgka-AmK9hcm4RQYZk',
    appId: '1:632357327788:web:f10586618ff61718ffa009',
    messagingSenderId: '632357327788',
    projectId: 'vetconnect-rural-2026-v1',
    authDomain: 'vetconnect-rural-2026-v1.firebaseapp.com',
    storageBucket: 'vetconnect-rural-2026-v1.firebasestorage.app',
  );
}
